const pairingShell = document.querySelector('#pairingShell');
const playerShell = document.querySelector('#playerShell');
const pairingForm = document.querySelector('#pairingForm');
const pairingCode = document.querySelector('#pairingCode');
const pairingError = document.querySelector('#pairingError');
const grid = document.querySelector('#runtimeGrid');
const visualQaMode = new URLSearchParams(window.location.search).get('board') === 'visual-qa';
const visualQaCelebration = visualQaMode && new URLSearchParams(window.location.search).get('celebration') === '1';
document.documentElement.dataset.visualQa = String(visualQaMode);
document.body.dataset.visualQa = String(visualQaMode);
const cacheKey = visualQaMode ? 'axoboard.display.visual-qa.last-good.v1' : 'axoboard.display.last-good.v1';
const automationCursorKey = visualQaMode ? 'axoboard.display.visual-qa.automation-cursor.v1' : 'axoboard.display.automation-cursor.v1';
const pageSize = 4;
let runtime = null;
let pageIndex = 0;
let rotationPaused = false;
let refreshSeconds = 45;
let rotationSeconds = 15;
let timer = null;
let automationPollSeconds = 1;
let automationCursor = (()=>{try{return localStorage.getItem(automationCursorKey)||new Date().toISOString();}catch{return new Date().toISOString();}})();
let celebrationTimer = null;
let celebrationActive = false;
let automationPolling = false;
let visualQaCelebrationQueued = false;
const celebrationQueue = [];
const seenCelebrationIds = new Set();

function escapeHtml(value) { return String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[character])); }
function clamp(value) { return Math.max(0, Math.min(100, Number(value) || 0)); }
function format(value, displayFormat = 'number') { const number = Number(value); if (!Number.isFinite(number)) return '—'; if (displayFormat === 'currency') return new Intl.NumberFormat(undefined, { style:'currency', currency:'USD', maximumFractionDigits:2 }).format(number); if (displayFormat === 'percentage') return new Intl.NumberFormat(undefined, { style:'percent', maximumFractionDigits:1 }).format(number/100); return new Intl.NumberFormat(undefined, { maximumFractionDigits:2 }).format(number); }
function timeAgo(value) { const timestamp = new Date(value).getTime(); if (!Number.isFinite(timestamp)) return 'waiting'; const seconds = Math.max(0,Math.round((Date.now()-timestamp)/1000)); if (seconds < 60) return `${seconds}s ago`; if (seconds < 3600) return `${Math.round(seconds/60)}m ago`; return `${Math.round(seconds/3600)}h ago`; }
async function api(path, options = {}) { const response = await fetch(path, { credentials:'include', headers:{ 'Content-Type':'application/json', ...(options.headers || {}) }, ...options }); const payload = await response.json().catch(()=>({})); if (!response.ok) { const error = new Error(payload.error || 'Request failed.'); error.status=response.status; error.code=payload.code; throw error; } return payload; }
function orderedKpis() { const kpis=runtime?.kpis || []; const order=runtime?.dashboard?.layout?.kpiOrder || []; const index=new Map(order.map((id,i)=>[id,i])); return [...kpis].sort((a,b)=>(index.get(a.id)??9999)-(index.get(b.id)??9999)); }
function context(kpi) { if (kpi.intelligence) return `${String(kpi.intelligence.status || '').replace('_',' ')} · projected ${format(kpi.intelligence.projectedFinish,kpi.displayFormat)}`; if (kpi.goalValue) return `${clamp(Number(kpi.value)/Number(kpi.goalValue)*100).toFixed(0)}% of goal`; return `${kpi.status === 'active' ? 'Live' : 'Needs attention'} · ${timeAgo(kpi.fetchedAt)}`; }
function meta(kpi) { const freshness=kpi.qa?.synthetic?(kpi.status==='active'?'Frozen fixture':'Stale fixture'):timeAgo(kpi.fetchedAt); return `<div class="card-meta"><span>${escapeHtml(kpi.qa?.synthetic ? 'Synthetic QA fixture · read only' : kpi.sheetTitle || 'Verified source')}</span><b>${escapeHtml(freshness)}</b></div>`; }
function heading(kpi) { const stale=kpi.status!=='active',label=kpi.qa?.synthetic?(stale?'Stale fixture':'Synthetic'):(stale?'Needs attention':'Live'); return `<header><div><small>${escapeHtml((kpi.displayType || 'scorecard').replaceAll('_',' '))}</small><h2>${escapeHtml(kpi.name)}</h2></div><span class="live-chip${stale?' is-stale':''}">● ${escapeHtml(label)}</span></header>`; }
function truncationCue(total, visible) { return total > visible ? `<small class="collection-cue">Showing ${visible} of ${total}</small>` : ''; }
function finite(value) { return value!==null&&value!==undefined&&value!==''&&Number.isFinite(Number(value)); }
function trend(items=[]) {
  const points=items.filter((item)=>finite(item.value));
  if(!points.length)return '<div class="visual-empty" data-qa-empty-state>No numeric trend points</div>';
  const values=points.flatMap((item)=>[item.value,item.comparisonValue].filter(finite).map(Number));
  let min=Math.min(...values),max=Math.max(...values);
  if(min===max){min-=1;max+=1;}
  const coords=(key)=>points.map((item,index)=>{if(!finite(item[key]))return null;const value=Number(item[key]),x=points.length===1?320:20+index/(points.length-1)*600,y=205-(value-min)/(max-min)*170;return `${x.toFixed(1)},${y.toFixed(1)}`;}).filter(Boolean).join(' ');
  const comparison=points.every((item)=>finite(item.comparisonValue))?`<polyline class="trend-comparison" points="${coords('comparisonValue')}"/>`:'';
  const comparisonDescription=comparison?`; comparison from ${points[0].comparisonValue} to ${points.at(-1).comparisonValue}`:'';
  return `<div class="trend" role="img" aria-label="Current trend from ${escapeHtml(points[0].label)} ${escapeHtml(points[0].value)} to ${escapeHtml(points.at(-1).label)} ${escapeHtml(points.at(-1).value)}${escapeHtml(comparisonDescription)}"><svg viewBox="0 0 640 220" preserveAspectRatio="none" aria-hidden="true"><line x1="20" y1="205" x2="620" y2="205"/>${comparison}<polyline class="trend-current" points="${coords('value')}"/></svg><div><span>${escapeHtml(points[0].label)}</span><span>${escapeHtml(points.at(-1).label)}</span></div></div>`;
}
function renderCard(kpi) {
  const type=kpi.displayType || 'scorecard', payload=kpi.displayPayload || {}, card=document.createElement('article'); card.className=`tv-card tv-card-${type}`; card.dataset.type=type; card.dataset.kpi=kpi.id;
  let body='';
  if(type==='gauge'){const value=Number(kpi.value),max=Number(kpi.goalValue)>0?Number(kpi.goalValue):Math.max(10,10**Math.ceil(Math.log10(Math.max(1,Math.abs(value))))),progress=clamp(value/max*100);body=`<div class="gauge" style="--turn:${progress/100}turn"><div><strong>${escapeHtml(format(value,kpi.displayFormat))}</strong><span>${progress.toFixed(1)}%</span></div></div>`;}
  else if(type==='goal_pace'){const target=Number(kpi.goalValue),hasGoal=Number.isFinite(target)&&target!==0,progress=hasGoal?clamp(Number(kpi.value)/target*100):0,remaining=hasGoal?Math.max(0,target-Number(kpi.value)):null,pace=kpi.intelligence?.requiredPerDay,projected=kpi.intelligence?.projectedFinish;body=`<div class="goal-pace-detail"><strong class="metric-value">${escapeHtml(format(kpi.value,kpi.displayFormat))}</strong><div class="metric-context">${escapeHtml(hasGoal?`${progress.toFixed(1)}% of ${format(target,kpi.displayFormat)}`:'Goal required')}</div><div class="progress"><i style="width:${progress}%"></i></div><div class="goal-pace-facts"><span><small>Projected</small><b>${escapeHtml(Number.isFinite(Number(projected))?format(projected,kpi.displayFormat):'Unavailable')}</b></span><span><small>Remaining</small><b>${escapeHtml(remaining===null?'Target needed':format(remaining,kpi.displayFormat))}</b></span><span><small>Required pace</small><b>${escapeHtml(Number.isFinite(Number(pace))?`${format(pace,kpi.displayFormat)}/day`:'Goal reached')}</b></span></div></div>`;}
  else if(type==='rep_cards'){const all=payload.items||[],items=all.slice(0,8);body=`<div class="rep-card-grid">${items.map((item)=>{const target=item.goalValue??item.comparisonValue??kpi.goalValue,progress=target?clamp(Number(item.value)/Number(target)*100):null;return `<article class="rep-card"><small>${escapeHtml(item.label)}</small><strong>${escapeHtml(format(item.value,kpi.displayFormat))}</strong><span>${progress===null?'Current value':`${progress.toFixed(0)}% of ${format(target,kpi.displayFormat)}`}</span><i><b style="width:${progress??100}%"></b></i></article>`;}).join('')}</div>${truncationCue(all.length,items.length)}`;}
  else if(type==='leaderboard'){const all=[...(payload.items||[])],items=[...all].sort((a,b)=>Number(b.value)-Number(a.value)).slice(0,8);body=`<div class="list">${items.map((item,i)=>`<div class="list-row"><b>${i+1}</b><span>${escapeHtml(item.label)}</span><strong>${escapeHtml(format(item.value,kpi.displayFormat))}</strong></div>`).join('')}${truncationCue(all.length,items.length)}</div>`;}
  else if(type==='trend')body=trend(payload.items);
  else if(type==='category_bar'){const all=payload.items||[],items=all.slice(0,8),max=Math.max(1,...items.map(x=>Math.abs(Number(x.value))));body=`<div class="bars">${items.map(item=>`<div class="bar-row"><span>${escapeHtml(item.label)}</span><i><b style="width:${clamp(Math.abs(Number(item.value))/max*100)}%"></b></i><strong>${escapeHtml(format(item.value,kpi.displayFormat))}</strong></div>`).join('')}${truncationCue(all.length,items.length)}</div>`;}
  else if(type==='funnel'){const all=payload.items||[],items=all.slice(0,7),max=Math.max(1,...items.map(x=>Math.abs(Number(x.value))));body=`<div class="funnel">${items.map((item,index)=>{const previous=index?Math.abs(Number(items[index-1].value)):null,conversion=previous?`${(Math.abs(Number(item.value))/previous*100).toFixed(0)}%`:'Start';return `<div style="width:${42+Math.abs(Number(item.value))/max*58}%"><span>${escapeHtml(item.label)}</span><strong>${escapeHtml(format(item.value,kpi.displayFormat))}</strong><small>${conversion}</small></div>`;}).join('')}${truncationCue(all.length,items.length)}</div>`;}
  else if(type==='pipeline'){const all=payload.items||[],items=all.slice(0,7);body=`<div class="flow">${items.map(item=>`<article title="${escapeHtml(item.label)}" aria-label="${escapeHtml(item.label)}: ${escapeHtml(format(item.value,kpi.displayFormat))}"><span>${escapeHtml(item.label)}</span><strong>${escapeHtml(format(item.value,kpi.displayFormat))}</strong></article>`).join('')}</div>${truncationCue(all.length,items.length)}`;}
  else if(type==='activity_feed'){const all=payload.entries||[],items=all.slice(0,7);body=items.length?`<div class="list">${items.map(entry=>`<div class="list-row"><b>${escapeHtml(entry.timestamp)}</b><span>${escapeHtml(entry.label)}${entry.detail?` · ${escapeHtml(entry.detail)}`:''}</span><strong>${entry.value!==null&&entry.value!==undefined&&entry.value!==''?escapeHtml(entry.value):''}</strong></div>`).join('')}${truncationCue(all.length,items.length)}</div>`:'<div class="visual-empty" data-qa-empty-state>No activity to show</div>';}
  else if(type==='heatmap'){const all=payload.yLabels||[],visible=all.slice(0,7),columns=Math.max(1,payload.xLabels?.length||1),range=Number(payload.max)-Number(payload.min)||1;body=`<div class="heatmap-scroll"><div class="heatmap" style="--columns:${columns}"><b>${escapeHtml(payload.cornerLabel||'')}</b>${(payload.xLabels||[]).map(x=>`<b>${escapeHtml(x)}</b>`).join('')}${visible.map((label,row)=>`<b>${escapeHtml(label)}</b>${(payload.cells?.[row]||[]).map(value=>`<i style="--heat:${.2+(Number(value)-Number(payload.min))/range*.8}">${escapeHtml(format(value,kpi.displayFormat))}</i>`).join('')}`).join('')}</div></div>${truncationCue(all.length,visible.length)}`;}
  else if(type==='table'){const all=payload.rows||[],rows=all.slice(0,8),columns=payload.columns||[];body=`<div class="table-scroll"><table class="data-table"><thead><tr>${columns.map(x=>`<th>${escapeHtml(x)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(row=>`<tr>${row.map(x=>`<td>${escapeHtml(x)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${Math.max(1,columns.length)}" data-qa-empty-state>No rows to show</td></tr>`}</tbody></table></div>${truncationCue(all.length,rows.length)}`;}
  else if(payload.layout==='rep_metric_goal'){const goal=Number(payload.goal?.value),progress=goal?clamp(Number(payload.metric?.value)/goal*100):0;body=`<div class="scorecard-detail"><div class="scorecard-rep"><small>${escapeHtml(payload.rep?.label||'Rep')}</small><strong>${escapeHtml(payload.rep?.value||'')}</strong></div><div class="scorecard-metric"><small>${escapeHtml(payload.metric?.label||kpi.name)}</small><strong class="metric-value">${escapeHtml(format(payload.metric?.value,kpi.displayFormat))}</strong></div><div class="scorecard-goal"><span><small>${escapeHtml(payload.goal?.label||'Goal')}</small><b>${escapeHtml(format(payload.goal?.value,kpi.displayFormat))}</b></span><strong>${goal?`${progress.toFixed(1)}%`:'Goal unavailable'}</strong></div><div class="progress"><i style="width:${progress}%"></i></div></div>`;}
  else {const progress=kpi.goalValue?clamp(Number(kpi.value)/Number(kpi.goalValue)*100):null;body=`<div><strong class="metric-value">${escapeHtml(format(kpi.value,kpi.displayFormat))}</strong><div class="metric-context">${escapeHtml(context(kpi))}</div>${progress===null?'':`<div class="progress"><i style="width:${progress}%"></i></div>`}</div>`;}
  card.innerHTML=`${heading(kpi)}<div class="card-body">${body}</div>${meta(kpi)}`; return card;
}
function applyBrand(){const tokens=runtime?.brand?.tokens||{};document.documentElement.style.setProperty('--customer-primary',tokens.primary||'#e96f98');document.documentElement.style.setProperty('--customer-secondary',tokens.secondary||'#43bde8');document.documentElement.style.setProperty('--customer-success',tokens.success||'#6ddb65');document.querySelector('#customerMark').textContent=(runtime?.brand?.name||runtime?.workspace?.name||'W').trim().charAt(0).toUpperCase();}
function render(){if(!runtime)return;applyBrand();const kpis=orderedKpis(),pages=Math.max(1,Math.ceil(kpis.length/pageSize));pageIndex=Math.min(pageIndex,pages-1);const visible=kpis.slice(pageIndex*pageSize,(pageIndex+1)*pageSize);grid.dataset.items=String(visible.length);grid.replaceChildren(...(visible.length?visible.map(renderCard):[Object.assign(document.createElement('article'),{className:'tv-card empty-card',innerHTML:'<strong>No KPIs assigned</strong><span>Choose dashboard content from the admin workspace.</span>'})]));document.querySelector('#runtimeTitle').textContent=runtime.visualQa?.active?'Visual QA board':runtime.display?.name||`${runtime.workspace?.name||'Workspace'} dashboard`;document.querySelector('#runtimeEyebrow').textContent=`${runtime.workspace?.name||'WORKSPACE'} · ${runtime.visualQa?.active?`${kpis.length} SYNTHETIC CARDS · `:''}PAGE ${pageIndex+1}/${pages}`.toUpperCase();document.querySelector('#runtimeFreshness').textContent=runtime.visualQa?.active?'Synthetic QA fixture · read only':kpis.length?`Latest verified ${timeAgo(kpis.reduce((a,b)=>new Date(a.fetchedAt)>new Date(b.fetchedAt)?a:b).fetchedAt)}`:'Waiting for assigned content';document.querySelector('#pageDots').innerHTML=Array.from({length:pages},(_,i)=>`<i class="${i===pageIndex?'is-active':''}"></i>`).join('');document.querySelector('#previousPage').disabled=pages<=1;document.querySelector('#nextPage').disabled=pages<=1;}
function setConnection(state){const label=document.querySelector('#runtimeConnection');label.dataset.state=state;label.textContent=state==='live'?(visualQaMode?'● QA fixture':'● Live'):state==='offline'?'● Last good view':'● Connecting';document.querySelector('#offlineBanner').hidden=state!=='offline';}
function closeAutomationCelebration(){window.clearTimeout(celebrationTimer);document.querySelector('#automationCelebration').hidden=true;celebrationActive=false;if(celebrationQueue.length)window.setTimeout(showNextAutomationCelebration,180);}
function showNextAutomationCelebration(){if(celebrationActive||!celebrationQueue.length)return;const event=celebrationQueue.shift(),overlay=document.querySelector('#automationCelebration'),durationMs=Math.max(2000,Math.min(60000,Number(event.durationSeconds||8)*1000));celebrationActive=true;overlay.dataset.theme=String(event.theme||'brand').slice(0,40);document.querySelector('#automationCelebrationMark').textContent=(runtime?.brand?.name||runtime?.workspace?.name||'W').trim().charAt(0).toUpperCase();document.querySelector('#automationCelebrationTitle').textContent=event.title||event.ruleName||'Goal reached';document.querySelector('#automationCelebrationMessage').textContent=event.message||'A trusted metric triggered this celebration.';document.querySelector('#automationCelebrationSource').textContent=visualQaMode?'Synthetic QA fixture · read only':event.metricName?`${event.metricName} · verified ${timeAgo(event.occurredAt)}`:`Verified ${timeAgo(event.occurredAt)}`;overlay.hidden=false;celebrationTimer=window.setTimeout(closeAutomationCelebration,durationMs);}
function enqueueAutomationCelebration(event){if(!event?.id||seenCelebrationIds.has(event.id))return;seenCelebrationIds.add(event.id);if(seenCelebrationIds.size>100)seenCelebrationIds.delete(seenCelebrationIds.values().next().value);celebrationQueue.push(event);showNextAutomationCelebration();}
async function loadAutomationEvents(){if(visualQaMode||!runtime||automationPolling)return;automationPolling=true;try{const payload=await api(`/api/display/automation-events?after=${encodeURIComponent(automationCursor)}`);const events=Array.isArray(payload.events)?payload.events:[];events.sort((a,b)=>new Date(a.occurredAt)-new Date(b.occurredAt)).forEach(enqueueAutomationCelebration);if(payload.cursor){automationCursor=payload.cursor;try{localStorage.setItem(automationCursorKey,automationCursor);}catch{}}}catch(error){if(error.status===401){clearCache();showPairing();}}finally{automationPolling=false;}}
function cacheRuntime(){try{localStorage.setItem(cacheKey,JSON.stringify({savedAt:Date.now(),runtime}));}catch{}}
function restoreCache(){try{const cached=JSON.parse(localStorage.getItem(cacheKey)||'null');if(cached?.runtime&&Date.now()-cached.savedAt<24*60*60*1000){runtime=cached.runtime;showPlayer();render();setConnection('offline');return true;}}catch{}return false;}
function clearCache(){window.clearTimeout(celebrationTimer);celebrationTimer=null;celebrationActive=false;automationCursor=new Date().toISOString();seenCelebrationIds.clear();celebrationQueue.length=0;runtime=null;pageIndex=0;const overlay=document.querySelector('#automationCelebration');if(overlay)overlay.hidden=true;try{localStorage.removeItem(cacheKey);localStorage.removeItem(automationCursorKey);}catch{}}
function showPlayer(){pairingShell.hidden=true;playerShell.hidden=false;}
function showPairing(){window.clearInterval(timer);playerShell.hidden=true;pairingShell.hidden=false;pairingCode.focus();}
async function loadRuntime(){try{const payload=await api(`/api/display/runtime${visualQaMode?'?board=visual-qa':''}`);runtime=payload;rotationSeconds=Math.max(5,Math.min(300,Number(payload.display?.rotationSeconds)||15));showPlayer();render();cacheRuntime();setConnection('live');if(visualQaCelebration&&!visualQaCelebrationQueued){visualQaCelebrationQueued=true;enqueueAutomationCelebration({id:'visual-qa-celebration',theme:'brand',title:'QA milestone unlocked',message:'This is a synthetic long-copy celebration used to verify wrapping, brand tokens, reduced motion, and safe display bounds across TV sizes.',metricName:'Visual QA fixture',occurredAt:new Date().toISOString(),durationSeconds:60});}return true;}catch(error){if(error.status===401){clearCache();showPairing();}else if(!runtime)restoreCache();else setConnection('offline');return false;}}
function movePage(delta){const pages=Math.max(1,Math.ceil(orderedKpis().length/pageSize));pageIndex=(pageIndex+delta+pages)%pages;rotationSeconds=Math.max(5,Number(runtime?.display?.rotationSeconds)||15);render();}
function updateClock(){const node=document.querySelector('#runtimeClock');node.dateTime=new Date().toISOString();node.textContent=new Intl.DateTimeFormat([],{hour:'numeric',minute:'2-digit'}).format(new Date());}
function startTimer(){window.clearInterval(timer);refreshSeconds=45;automationPollSeconds=1;rotationSeconds=Math.max(5,Number(runtime?.display?.rotationSeconds)||15);timer=window.setInterval(async()=>{refreshSeconds-=1;automationPollSeconds-=1;if(!rotationPaused&&orderedKpis().length>pageSize)rotationSeconds-=1;if(rotationSeconds<=0)movePage(1);if(refreshSeconds<=0){refreshSeconds=45;await loadRuntime();}if(automationPollSeconds<=0){automationPollSeconds=5;await loadAutomationEvents();}document.querySelector('#refreshCountdown').textContent=refreshSeconds;updateClock();},1000);}
pairingCode.addEventListener('input',()=>{pairingCode.value=pairingCode.value.toUpperCase().replace(/[^2-9A-HJ-NP-Z]/g,'').slice(0,8);pairingError.textContent='';});
pairingForm.addEventListener('submit',async event=>{event.preventDefault();const button=pairingForm.querySelector('button');button.disabled=true;pairingError.textContent='';try{await api('/api/display/pair',{method:'POST',body:JSON.stringify({code:pairingCode.value})});pairingCode.value='';await loadRuntime();startTimer();}catch(error){pairingError.textContent=error.message;}finally{button.disabled=false;}});
document.querySelector('#previousPage').addEventListener('click',()=>movePage(-1));document.querySelector('#nextPage').addEventListener('click',()=>movePage(1));document.querySelector('#pauseRotation').addEventListener('click',event=>{rotationPaused=!rotationPaused;event.currentTarget.textContent=rotationPaused?'Resume':'Pause';event.currentTarget.setAttribute('aria-pressed',String(rotationPaused));});document.querySelector('#fullscreenButton').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{}});document.addEventListener('fullscreenchange',()=>{const button=document.querySelector('#fullscreenButton');button.textContent=document.fullscreenElement?'↙':'⛶';button.setAttribute('aria-label',document.fullscreenElement?'Exit fullscreen':'Enter fullscreen');});window.addEventListener('online',()=>{setConnection('loading');loadRuntime();});window.addEventListener('offline',()=>setConnection('offline'));document.addEventListener('keydown',event=>{if(playerShell.hidden)return;if(event.key==='ArrowRight')movePage(1);else if(event.key==='ArrowLeft')movePage(-1);else if(event.key===' '||event.key.toLowerCase()==='p')document.querySelector('#pauseRotation').click();else if(event.key.toLowerCase()==='f')document.querySelector('#fullscreenButton').click();});
document.querySelector('#dismissAutomationCelebration').addEventListener('click',closeAutomationCelebration);
(async()=>{updateClock();try{const status=await api('/api/display/status');if(status.paired)await loadRuntime();else{clearCache();showPairing();}}catch{restoreCache();}if(runtime)startTimer();})();
