const pairingShell = document.querySelector('#pairingShell');
const playerShell = document.querySelector('#playerShell');
const pairingForm = document.querySelector('#pairingForm');
const pairingCode = document.querySelector('#pairingCode');
const pairingError = document.querySelector('#pairingError');
const grid = document.querySelector('#runtimeGrid');
const cacheKey = 'axoboard.display.last-good.v1';
const pageSize = 4;
let runtime = null;
let pageIndex = 0;
let rotationPaused = false;
let refreshSeconds = 45;
let rotationSeconds = 15;
let timer = null;

function escapeHtml(value) { return String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[character])); }
function clamp(value) { return Math.max(0, Math.min(100, Number(value) || 0)); }
function format(value, displayFormat = 'number') { const number = Number(value); if (!Number.isFinite(number)) return String(value ?? '—'); if (displayFormat === 'currency') return new Intl.NumberFormat([], { style:'currency', currency:'USD', maximumFractionDigits:number >= 1000 ? 0 : 2 }).format(number); if (displayFormat === 'percentage') return `${number.toLocaleString(undefined,{maximumFractionDigits:1})}%`; return number.toLocaleString(undefined,{maximumFractionDigits:2}); }
function timeAgo(value) { const timestamp = new Date(value).getTime(); if (!Number.isFinite(timestamp)) return 'waiting'; const seconds = Math.max(0,Math.round((Date.now()-timestamp)/1000)); if (seconds < 60) return `${seconds}s ago`; if (seconds < 3600) return `${Math.round(seconds/60)}m ago`; return `${Math.round(seconds/3600)}h ago`; }
async function api(path, options = {}) { const response = await fetch(path, { credentials:'include', headers:{ 'Content-Type':'application/json', ...(options.headers || {}) }, ...options }); const payload = await response.json().catch(()=>({})); if (!response.ok) { const error = new Error(payload.error || 'Request failed.'); error.status=response.status; error.code=payload.code; throw error; } return payload; }
function orderedKpis() { const kpis=runtime?.kpis || []; const order=runtime?.dashboard?.layout?.kpiOrder || []; const index=new Map(order.map((id,i)=>[id,i])); return [...kpis].sort((a,b)=>(index.get(a.id)??9999)-(index.get(b.id)??9999)); }
function context(kpi) { if (kpi.intelligence) return `${String(kpi.intelligence.status || '').replace('_',' ')} · projected ${format(kpi.intelligence.projectedFinish,kpi.displayFormat)}`; if (kpi.goalValue) return `${clamp(Number(kpi.value)/Number(kpi.goalValue)*100).toFixed(0)}% of goal`; return `${kpi.status === 'active' ? 'Live' : 'Needs attention'} · ${timeAgo(kpi.fetchedAt)}`; }
function meta(kpi) { return `<div class="card-meta"><span>${escapeHtml(kpi.sheetTitle || 'Google Sheets')}</span><b>${escapeHtml(timeAgo(kpi.fetchedAt))}</b></div>`; }
function heading(kpi) { return `<header><div><small>${escapeHtml((kpi.displayType || 'scorecard').replaceAll('_',' '))}</small><h2>${escapeHtml(kpi.name)}</h2></div><span class="live-chip">● Live</span></header>`; }
function trend(items=[]) { const points=items.filter(x=>Number.isFinite(Number(x.value))); if(!points.length)return '<span>No numeric trend points</span>'; const values=points.map(x=>Number(x.value)),min=Math.min(...values),max=Math.max(...values),range=max-min||1; const coords=points.map((x,i)=>`${points.length===1?320:20+i/(points.length-1)*600},${205-(Number(x.value)-min)/range*170}`).join(' '); return `<div class="trend"><svg viewBox="0 0 640 220" preserveAspectRatio="none"><line x1="20" y1="205" x2="620" y2="205"/><polyline points="${coords}"/></svg><div><span>${escapeHtml(points[0].label)}</span><span>${escapeHtml(points.at(-1).label)}</span></div></div>`; }
function renderCard(kpi) {
  const type=kpi.displayType || 'scorecard', payload=kpi.displayPayload || {}, card=document.createElement('article'); card.className=`tv-card tv-card-${type}`; card.dataset.type=type;
  let body='';
  if(type==='gauge'){const value=Number(kpi.value),max=Number(kpi.goalValue)>0?Number(kpi.goalValue):Math.max(10,10**Math.ceil(Math.log10(Math.max(1,Math.abs(value))))),progress=clamp(value/max*100);body=`<div class="gauge" style="--turn:${progress/100}turn"><div><strong>${escapeHtml(format(value,kpi.displayFormat))}</strong><span>${progress.toFixed(1)}%</span></div></div>`;}
  else if(type==='goal_pace'){const target=Number(kpi.goalValue),progress=target?clamp(Number(kpi.value)/target*100):0,pace=kpi.intelligence?.requiredPerDay;body=`<div><strong class="metric-value">${escapeHtml(format(kpi.value,kpi.displayFormat))}</strong><div class="metric-context">${escapeHtml(kpi.intelligence ? `${String(kpi.intelligence.status).replace('_',' ')} · ${pace ? `${format(pace,kpi.displayFormat)}/day required` : 'goal reached'}` : target ? `${progress.toFixed(1)}% of ${format(target,kpi.displayFormat)}` : 'Goal required')}</div><div class="progress"><i style="width:${progress}%"></i></div></div>`;}
  else if(['leaderboard','rep_cards'].includes(type)){const items=[...(payload.items||[])].sort(type==='leaderboard'?(a,b)=>Number(b.value)-Number(a.value):()=>0).slice(0,8);body=`<div class="list">${items.map((item,i)=>`<div class="list-row"><b>${type==='leaderboard'?i+1:'•'}</b><span>${escapeHtml(item.label)}</span><strong>${escapeHtml(format(item.value,kpi.displayFormat))}</strong></div>`).join('')}</div>`;}
  else if(type==='trend')body=trend(payload.items);
  else if(type==='category_bar'){const items=(payload.items||[]).slice(0,8),max=Math.max(1,...items.map(x=>Math.abs(Number(x.value))));body=`<div class="bars">${items.map(item=>`<div class="bar-row"><span>${escapeHtml(item.label)}</span><i><b style="width:${clamp(Math.abs(Number(item.value))/max*100)}%"></b></i><strong>${escapeHtml(format(item.value,kpi.displayFormat))}</strong></div>`).join('')}</div>`;}
  else if(type==='funnel'){const items=(payload.items||[]).slice(0,7),max=Math.max(1,...items.map(x=>Math.abs(Number(x.value))));body=`<div class="funnel">${items.map(item=>`<div style="width:${42+Math.abs(Number(item.value))/max*58}%"><span>${escapeHtml(item.label)}</span><strong>${escapeHtml(format(item.value,kpi.displayFormat))}</strong></div>`).join('')}</div>`;}
  else if(type==='pipeline'){body=`<div class="flow">${(payload.items||[]).slice(0,7).map(item=>`<article><span>${escapeHtml(item.label)}</span><strong>${escapeHtml(format(item.value,kpi.displayFormat))}</strong></article>`).join('')}</div>`;}
  else if(type==='activity_feed'){body=`<div class="list">${(payload.entries||[]).slice(0,7).map(entry=>`<div class="list-row"><b>${escapeHtml(entry.timestamp)}</b><span>${escapeHtml(entry.label)}${entry.detail?` · ${escapeHtml(entry.detail)}`:''}</span><strong>${escapeHtml(entry.value||'')}</strong></div>`).join('')}</div>`;}
  else if(type==='heatmap'){const columns=Math.max(1,payload.xLabels?.length||1),range=Number(payload.max)-Number(payload.min)||1;body=`<div class="heatmap-scroll"><div class="heatmap" style="--columns:${columns}"><b>${escapeHtml(payload.cornerLabel||'')}</b>${(payload.xLabels||[]).map(x=>`<b>${escapeHtml(x)}</b>`).join('')}${(payload.yLabels||[]).slice(0,7).map((label,row)=>`<b>${escapeHtml(label)}</b>${(payload.cells?.[row]||[]).map(value=>`<i style="--heat:${.2+(Number(value)-Number(payload.min))/range*.8}">${escapeHtml(format(value,kpi.displayFormat))}</i>`).join('')}`).join('')}</div></div>`;}
  else if(type==='table'){body=`<div class="table-scroll"><table class="data-table"><thead><tr>${(payload.columns||[]).map(x=>`<th>${escapeHtml(x)}</th>`).join('')}</tr></thead><tbody>${(payload.rows||[]).slice(0,8).map(row=>`<tr>${row.map(x=>`<td>${escapeHtml(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
  else if(payload.layout==='rep_metric_goal'){const progress=payload.goal?.value?clamp(Number(payload.metric.value)/Number(payload.goal.value)*100):0;body=`<div><small>${escapeHtml(payload.rep?.label||'Rep')}</small><div class="metric-context">${escapeHtml(payload.rep?.value||'')}</div><strong class="metric-value">${escapeHtml(format(payload.metric?.value,kpi.displayFormat))}</strong><div class="progress"><i style="width:${progress}%"></i></div></div>`;}
  else {const progress=kpi.goalValue?clamp(Number(kpi.value)/Number(kpi.goalValue)*100):null;body=`<div><strong class="metric-value">${escapeHtml(format(kpi.value,kpi.displayFormat))}</strong><div class="metric-context">${escapeHtml(context(kpi))}</div>${progress===null?'':`<div class="progress"><i style="width:${progress}%"></i></div>`}</div>`;}
  card.innerHTML=`${heading(kpi)}<div class="card-body">${body}</div>${meta(kpi)}`; return card;
}
function applyBrand(){const tokens=runtime?.brand?.tokens||{};document.documentElement.style.setProperty('--customer-primary',tokens.primary||'#e96f98');document.documentElement.style.setProperty('--customer-secondary',tokens.secondary||'#43bde8');document.documentElement.style.setProperty('--customer-success',tokens.success||'#6ddb65');document.querySelector('#customerMark').textContent=(runtime?.brand?.name||runtime?.workspace?.name||'W').trim().charAt(0).toUpperCase();}
function render(){if(!runtime)return;applyBrand();const kpis=orderedKpis(),pages=Math.max(1,Math.ceil(kpis.length/pageSize));pageIndex=Math.min(pageIndex,pages-1);const visible=kpis.slice(pageIndex*pageSize,(pageIndex+1)*pageSize);grid.dataset.items=String(visible.length);grid.replaceChildren(...(visible.length?visible.map(renderCard):[Object.assign(document.createElement('article'),{className:'tv-card empty-card',innerHTML:'<strong>No KPIs assigned</strong><span>Choose dashboard content from the admin workspace.</span>'})]));document.querySelector('#runtimeTitle').textContent=runtime.display?.name||`${runtime.workspace?.name||'Workspace'} dashboard`;document.querySelector('#runtimeEyebrow').textContent=`${runtime.workspace?.name||'WORKSPACE'} · PAGE ${pageIndex+1}/${pages}`.toUpperCase();document.querySelector('#runtimeFreshness').textContent=kpis.length?`Latest verified ${timeAgo(kpis.reduce((a,b)=>new Date(a.fetchedAt)>new Date(b.fetchedAt)?a:b).fetchedAt)}`:'Waiting for assigned content';document.querySelector('#pageDots').innerHTML=Array.from({length:pages},(_,i)=>`<i class="${i===pageIndex?'is-active':''}"></i>`).join('');document.querySelector('#previousPage').disabled=pages<=1;document.querySelector('#nextPage').disabled=pages<=1;}
function setConnection(state){const label=document.querySelector('#runtimeConnection');label.dataset.state=state;label.textContent=state==='live'?'● Live':state==='offline'?'● Last good view':'● Connecting';document.querySelector('#offlineBanner').hidden=state!=='offline';}
function cacheRuntime(){try{localStorage.setItem(cacheKey,JSON.stringify({savedAt:Date.now(),runtime}));}catch{}}
function restoreCache(){try{const cached=JSON.parse(localStorage.getItem(cacheKey)||'null');if(cached?.runtime&&Date.now()-cached.savedAt<24*60*60*1000){runtime=cached.runtime;showPlayer();render();setConnection('offline');return true;}}catch{}return false;}
function clearCache(){try{localStorage.removeItem(cacheKey);}catch{}}
function showPlayer(){pairingShell.hidden=true;playerShell.hidden=false;}
function showPairing(){window.clearInterval(timer);playerShell.hidden=true;pairingShell.hidden=false;pairingCode.focus();}
async function loadRuntime(){try{const payload=await api('/api/display/runtime');runtime=payload;rotationSeconds=Math.max(5,Math.min(300,Number(payload.display?.rotationSeconds)||15));showPlayer();render();cacheRuntime();setConnection('live');return true;}catch(error){if(error.status===401){clearCache();showPairing();}else if(!runtime)restoreCache();else setConnection('offline');return false;}}
function movePage(delta){const pages=Math.max(1,Math.ceil(orderedKpis().length/pageSize));pageIndex=(pageIndex+delta+pages)%pages;rotationSeconds=Math.max(5,Number(runtime?.display?.rotationSeconds)||15);render();}
function updateClock(){const node=document.querySelector('#runtimeClock');node.dateTime=new Date().toISOString();node.textContent=new Intl.DateTimeFormat([],{hour:'numeric',minute:'2-digit'}).format(new Date());}
function startTimer(){window.clearInterval(timer);refreshSeconds=45;rotationSeconds=Math.max(5,Number(runtime?.display?.rotationSeconds)||15);timer=window.setInterval(async()=>{refreshSeconds-=1;if(!rotationPaused&&orderedKpis().length>pageSize)rotationSeconds-=1;if(rotationSeconds<=0)movePage(1);if(refreshSeconds<=0){refreshSeconds=45;await loadRuntime();}document.querySelector('#refreshCountdown').textContent=refreshSeconds;updateClock();},1000);}
pairingCode.addEventListener('input',()=>{pairingCode.value=pairingCode.value.toUpperCase().replace(/[^2-9A-HJ-NP-Z]/g,'').slice(0,8);pairingError.textContent='';});
pairingForm.addEventListener('submit',async event=>{event.preventDefault();const button=pairingForm.querySelector('button');button.disabled=true;pairingError.textContent='';try{await api('/api/display/pair',{method:'POST',body:JSON.stringify({code:pairingCode.value})});pairingCode.value='';await loadRuntime();startTimer();}catch(error){pairingError.textContent=error.message;}finally{button.disabled=false;}});
document.querySelector('#previousPage').addEventListener('click',()=>movePage(-1));document.querySelector('#nextPage').addEventListener('click',()=>movePage(1));document.querySelector('#pauseRotation').addEventListener('click',event=>{rotationPaused=!rotationPaused;event.currentTarget.textContent=rotationPaused?'Resume':'Pause';event.currentTarget.setAttribute('aria-pressed',String(rotationPaused));});document.querySelector('#fullscreenButton').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{}});document.addEventListener('fullscreenchange',()=>{const button=document.querySelector('#fullscreenButton');button.textContent=document.fullscreenElement?'↙':'⛶';button.setAttribute('aria-label',document.fullscreenElement?'Exit fullscreen':'Enter fullscreen');});window.addEventListener('online',()=>{setConnection('loading');loadRuntime();});window.addEventListener('offline',()=>setConnection('offline'));document.addEventListener('keydown',event=>{if(playerShell.hidden)return;if(event.key==='ArrowRight')movePage(1);else if(event.key==='ArrowLeft')movePage(-1);else if(event.key===' '||event.key.toLowerCase()==='p')document.querySelector('#pauseRotation').click();else if(event.key.toLowerCase()==='f')document.querySelector('#fullscreenButton').click();});
(async()=>{updateClock();try{const status=await api('/api/display/status');if(status.paired)await loadRuntime();else{clearCache();showPairing();}}catch{restoreCache();}if(runtime)startTimer();})();
